### ISSUE TITLE
&time doesn't accept fractional timezones 

### ISSUE THREAD

**Issue by Helzibah** [grickit/Gambot#36]
These work as expected for timezone maths:

```
<Helzibah> &time
<janebot> Helzibah: 11:55:06 (UTC+0)
<Helzibah> &time -1
<janebot> Helzibah: 10:55:06 (UTC-1)
```

However, not all timezones are hour-aligned, there are many at :30, and a few at :15 or :45.  Neither of these syntaxes work:

```
<Helzibah> &time -1.5
<janebot> Helzibah: No way.
<Helzibah> &time -1:30
<janebot> Helzibah: Of course not!
```

[Edit]:

Whilst we're at it... ``&time 5`` should just alias to ``&time +5`` rather than failing.

**Comment by grickit** [comment]
Implemented in commit c21c0df
