### ISSUE TITLE
Format Youtube duration output

### ISSUE THREAD

**Issue by Helzibah** [grickit/Gambot#42]
*Issue*: The current '5M45S' time output is surprisingly difficult to read; particularly distinguising between 5 and S makes it very hard to scan for a time.

*Expected result*: [5:45] as previously seen

*Other comments*: if it's a pain, just lowercasing to '5m45s' would make it significantly more readable.

**Comment by dariota** [comment]
Partially fixed with my [PR](https://github.com/grickit/Gambot/pull/47). Since I can't perl I just lowercased it.

**Comment by grickit** [comment]
Fixed in commit b161d3e
