### ISSUE TITLE
Match words in &remember on word boundaries

### ISSUE THREAD

**Issue by dariota** [grickit/Gambot#74]
&remember seems te be working off a simple substring check rather than a check on word boundaries which, paired with some unknown issue preventing some messages from being remembered causes situations like the below.

```
<x10A94> Blow me.
<yoho> &remember x10A94 blow
<janebot> yoho: I don't remember what x10A94 said about blow
<x10A94> Huh, why wouldn't it remember the quote?
<yoho> &remember x10A94 me
<janebot> yoho: Remembered "Huh, why wouldn't it remember the quote?" - x10A94 7 (2016-08-06)
```

**Comment by Dinnerbone** [comment]
It's possible that it was just a race condition, as I saw that the message "blow me" was at the same time as another message. The memory module sadly can lose a message if another one comes in at the same time, because of how the internal API is structured :(

**Comment by dariota** [comment]
Hm, the messages came far enough apart for me that their timestamps don't match to the second.

As an aside, TIL angle brackets need escaping in GitHub comments.

**Comment by Dinnerbone** [comment]
For me, there was another message at the same second. IRC servers are sadly imprecise, people see messages slightly offset depending on which server they're using :D
